import { ObjectId } from "mongodb";

declare module "mongodb" {
  interface Post {
    id?: string;
    _id?: string;
    creator?: User;
    prompt: string;
    tag?: string;
    shared?: boolean;
    isFavorite?: boolean;
  }

  interface User {
    id?: string;
    _id?: string;
    email: string;
    username: string;
    image: string;
    favorites: Post[];
  }

  interface UserFavorite {
    _id: string;
    userId: string;
    postId: PostID;
  }

  interface PostID {
    _id: string;
    creator: Creator;
    prompt: string;
    tag: string;
    shared: boolean;
  }

  interface Creator {
    _id: string;
    email: string;
    username: string;
    image: string;
  }
}

// Generated by https://quicktype.io
